In [380]:
# Initialize Otter
import otter
grader = otter.Notebook("lab.ipynb")

# Lab 9 ‚Äì Models and Pipelines üîÅ

## DSC 80, Winter 2024

### Due Date: Monday, March 11th at 11:59PM

## Instructions

Welcome to the ninth and final DSC 80 lab this quarter!

Much like in DSC 10, this Jupyter Notebook contains the statements of the problems and provides code and Markdown cells to display your answers to the problems. Unlike DSC 10, the notebook is *only* for displaying a readable version of your final answers. The coding will be done in an accompanying `lab.py` file that is imported into the current notebook, and **you will only submit that `lab.py` file**, not this notebook!

Some additional guidelines:
- **Unlike in DSC 10, labs will have both public tests and hidden tests.** The bulk of your grade will come from your scores on hidden tests, which you will only see on Gradescope after the assignment deadline.
- **Do not change the function names in the `lab.py` file!** The functions in the `lab.py` file are how your assignment is graded, and they are graded by their name. If you changed something you weren't supposed to, you can find the original code in the [course GitHub repository](https://github.com/dsc-courses/dsc80-2024-wi).
- Notebooks are nice for testing and experimenting with different implementations before designing your function in your `lab.py` file. You can write code here, but make sure that all of your real work is in the `lab.py` file, since that's all you're submitting.
- You are encouraged to write your own additional helper functions to solve the lab, as long as they also end up in `lab.py`.

**To ensure that all of the work you want to submit is in `lab.py`, we've included a script named `lab-validation.py` in the lab folder. You shouldn't edit it, but instead, you should call it from the command line (e.g. the Terminal) to test your work.** More details on its usage are given at the bottom of this notebook.

**Importing code from `lab.py`**:

* Below, we import the `.py` file that's contained in the same directory as this notebook.
* We use the `autoreload` notebook extension to make changes to our `lab.py` file immediately available in our notebook. Without this extension, we would need to restart the notebook kernel to see any changes to `lab.py` in the notebook.
    - `autoreload` is necessary because, upon import, `lab.py` is compiled to bytecode (in the directory `__pycache__`). Subsequent imports of `lab` merely import the existing compiled python.

In [381]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [382]:
from lab import *

In [383]:
import pandas as pd
import numpy as np
from pathlib import Path
import plotly.express as px

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from pipeline_testing_util import get_transformers

from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.io as pio

import warnings
warnings.simplefilter('ignore')

# DSC 80 preferred styles
pio.templates["dsc80"] = go.layout.Template(
    layout=dict(
        margin=dict(l=30, r=30, t=30, b=30),
        autosize=True,
        width=800,
        height=500,
        xaxis=dict(showgrid=True),
        yaxis=dict(showgrid=True),
        title=dict(x=0.5, xanchor="center"),
    )
)
pio.templates.default = "simple_white+dsc80"

## Part 1: `sklearn` Pipelines üß†

The file `data/toy.csv` contains an example dataset that consists of 4 columns:

- `'group'`: a categorical column with 3 categories
- `'c1'`: a numeric attribute
- `'c2'`: a numeric attribute
- `'y'`: the target variable (that you want to predict) 
```

In the following questions, you will build `Pipeline`s that combine feature engineering with a linear regression model.

In [384]:
fp = Path('data') / 'toy.csv'
data = pd.read_csv(fp)
data.head()

  group        c1         c2          y
0     B  4.058118   5.329582  12.649035
1     A  4.194945   3.839476  17.309083
2     A  2.246411  10.694666  15.695646
3     B  2.510912   6.414960  11.535752
4     B  3.194722   6.116839  14.954389

### Question 1

First, you will train a regression model using only a *log-scaled* `'c2'` variable. Create a `Pipeline` that:
1. log-scales `'c2'`, then
2. predicts `'y'` using a linear regression model (using your transformed `'c2'`).

That is, complete the implementation of the function `simple_pipeline`, which takes in a DataFrame like `data` and returns a **tuple** consisting of 
- An already-fit `Pipeline`, and
- An array containing the predictions your model makes on `data` (after being trained on `data`).

***Note***: By "log", we're referring to the natural logarithm. In order to log-scale `'c2'`, you'll need to use a `FunctionTransformer`.

In [385]:
# don't change this cell, but do run it -- it is needed for the tests to work
q1_fp = Path('data') / 'toy.csv'
q1_data = pd.read_csv(q1_fp)
q1_pl, q1_preds = simple_pipeline(q1_data)

In [386]:
simple_pipeline(q1_data)

(Pipeline(steps=[('log-scales', FunctionTransformer(func=<ufunc 'log'>)),
                 ('Linear Regression', LinearRegression())]),
 array([12.62080258, 11.33240999, 15.35709202, 13.34904182, 13.16208199,
        12.58730638, 10.32010771,  9.97565958, 12.4341862 ,  9.97565958,
        11.00176451, 11.72576886, 13.29324648, 13.52069629, 12.69877755,
        16.56022602, 10.90515178, 11.59328864, 13.75185396, 10.13914047,
        16.45741691, 12.22981832, 10.03041175, 13.6458863 , 10.40933462,
         9.97565958, 12.6181805 , 13.2395772 , 17.80416143,  9.97565958,
        17.31864025, 11.70631644, 10.04917783, 13.54303459, 10.23465198,
         9.97565958,  9.97565958, 14.13802627, 15.54064641,  9.97565958,
         9.97565958, 15.66902784,  9.97565958, 14.88720712, 10.67109288,
        11.29811807, 13.80545472, 10.23529717, 10.40456903, 13.08402701,
         9.97565958,  9.97565958,  9.97565958,  9.97565958, 15.10329322,
        12.32722694, 13.95698297,  9.97565958,  9.97565958,  9.97565958,
         9.97565958, 11.05800145,  9.97565958,  9.97565958, 13.77397551,
        17.70287735, 10.31042233, 15.31536588, 16.33383322,  9.97565958,
        14.97079869,  9.97565958,  9.98941903,  9.97565958,  9.97565958,
        12.13115627, 13.08264655, 10.7803003 , 10.10361658, 12.50925298,
        11.81374969,  9.97565958, 13.92511727, 12.32665705, 16.39950047,
        12.03158679, 13.53876868, 10.51132597, 10.54800032,  9.97565958,
        11.77860887, 11.85689079,  9.97565958,  9.97565958,  9.97565958,
        15.30979672, 12.83403068,  9.97565958,  9.97565958, 12.48678172,
        12.83662321, 17.19677166,  9.97565958, 11.07949006, 11.75638585,
         9.97565958,  9.97565958, 15.48895222, 16.44897237, 10.22508261,
        11.76346936, 10.65584042,  9.97565958, 13.36049064, 12.94928047,
         9.97565958, 15.21954177,  9.97565958,  9.97565958, 13.54993378,
        13.561096  , 14.43596118,  9.97565958, 11.55771178,  9.97565958,
         9.97565958, 13.27936289, 10.25134273, 12.99433539, 12.24478839,
        17.16461764, 16.16340779, 11.91935422,  9.97565958, 12.91275162,
        12.06812144, 13.70607754, 10.93894617,  9.97565958,  9.97565958,
        16.95568066, 14.17948161,  9.97565958, 10.09150604,  9.97565958,
         9.97565958, 15.5245347 , 15.69166602,  9.97565958, 12.16121561,
         9.97565958, 15.20778645,  9.97565958, 13.66935098, 12.85299909,
        11.1169081 ,  9.97565958, 13.15247854, 13.17396895,  9.97565958,
         9.97565958, 10.67882736,  9.97565958, 15.11138844, 11.59727103,
        11.60776838,  9.97565958,  9.97565958, 11.37678765,  9.97565958,
         9.97565958, 10.78401688, 16.61547736, 11.65824063, 16.61259132,
        11.17821344, 10.22916637, 11.37745497, 11.31561077, 11.95768093,
        12.44785701, 11.52709598, 14.51876791, 11.25801369,  9.97565958,
        16.95047842, 15.66171267,  9.97565958,  9.97565958, 12.46368585,
        13.33723475,  9.97565958, 11.42996096,  9.99737386, 12.35950949,
        13.35478251, 10.19181867, 12.92463884, 16.97302338, 17.57926795,
        11.87437159, 11.77028686, 11.8893785 , 15.99889197, 15.36768212,
         9.97565958,  9.97565958,  9.97565958, 12.87627787, 17.09109771,
        17.45244492, 11.61042586, 10.66161341, 15.33385765, 12.58358769,
        12.68124667, 16.05583385, 15.22617885,  9.97565958, 11.57587922,
         9.97565958,  9.97565958,  9.97565958,  9.97565958,  9.97565958,
        10.01440475, 13.86781388, 12.19758444, 13.62519929,  9.97565958,
         9.97565958, 11.22330338,  9.97565958, 13.32666444, 11.04178574,
        11.3693541 , 17.19195619, 11.20587562, 17.01821599,  9.97565958,
        11.88632292, 12.80093113, 15.50143365, 12.77772219,  9.97565958,
        10.41193255,  9.97565958, 14.51204242,  9.97565958,  9.97565958,
        10.27706103, 10.04047086,  9.97565958, 13.02676223,  9.97565958,
         9.97565958,  9.97565958, 12.74344643,  9.97565958, 11.46221303,
         9.97565958,  9.97565958, 10.93915291, 10.35627437,  9.97565958,
        13.11539395,  9.97565958,  9.97565958,  9.97565958, 10.52865504,
         9.97565958, 10.52971618, 13.22522968, 14.04751392,  9.97565958,
         9.97565958, 17.69846674, 17.61394016,  9.97565958, 12.04230792,
        10.75025581, 10.40807705, 10.75233232,  9.97565958, 13.38179119,
         9.97565958, 16.96040179,  9.97565958,  9.97565958, 11.81973849,
        16.8108996 , 15.30804614, 11.25883912,  9.97565958, 11.12233312,
         9.97565958, 13.13982838,  9.97565958, 13.76442954, 10.46288759,
        10.62007072,  9.97565958, 12.32083736, 10.81357597, 11.12772182,
         9.97565958,  9.97565958, 13.41439573,  9.97565958,  9.97565958,
        16.97055326, 11.49112927, 10.4981806 ,  9.97565958, 15.78959252,
         9.97565958, 11.46653935,  9.97565958, 10.32845142, 13.05367366,
        15.33809366, 10.65945241, 13.18366573,  9.97565958,  9.97565958,
        13.71013213, 13.74644658, 11.90355806,  9.97565958, 16.47962223,
         9.97565958, 17.82545175, 13.07417451, 14.09228198,  9.97565958,
        11.67483493, 10.59804431, 12.63698105, 12.76283502, 10.28237809,
        15.78219854, 13.3691373 , 10.99163155,  9.97565958, 10.10603872,
        17.58320268, 10.43602798, 11.70814523, 10.1618998 , 10.27285872,
        13.12108083, 12.19997426, 13.83270531,  9.97565958, 12.41565244,
         9.97565958, 13.43423824, 10.0902715 , 16.74339555, 10.46035902,
        12.78781094, 16.1490684 ,  9.97565958,  9.97565958,  9.97565958,
        12.55975452, 16.07801388, 12.75242448,  9.97565958,  9.97565958,
        14.4994008 , 17.18366433, 11.21256101, 12.40302373,  9.97565958,
         9.97565958, 11.38528483, 11.97882261,  9.97565958,  9.97565958,
        15.93974844,  9.97565958, 10.35542641, 10.90812587, 13.81281609,
        15.15556833,  9.97565958, 13.37815447, 15.38691098,  9.97565958,
         9.99971641, 17.32061718, 10.7555004 , 10.63219403, 13.48690591,
        15.69198269,  9.97565958, 13.04596471, 13.43805111,  9.97565958,
         9.97565958, 14.042934  ,  9.97565958, 15.92840483, 16.82167524,
        14.22093142, 13.76276229, 17.71516554, 15.88755989, 12.9449486 ,
        17.71546077,  9.97565958, 11.31295278, 13.70127095, 10.3780194 ,
        11.76161729, 14.71961744,  9.97565958,  9.97565958,  9.97565958,
         9.97565958, 17.64075363, 10.92989648, 10.91755973, 10.73117707,
        10.15927622,  9.97565958,  9.97565958, 13.59399732, 12.9357942 ,
        15.40366445, 10.90862295, 13.73589925, 17.70347119, 13.27571655,
         9.97565958, 11.97818654,  9.97565958, 14.08321257, 10.75929469,
        11.10898544,  9.97565958, 13.68355085,  9.97565958, 11.98825433,
        12.80707139, 11.50966114,  9.97565958, 13.58303118, 10.60642725,
         9.97565958, 16.72318793, 12.3264533 ,  9.97565958, 15.2184814 ,
        13.29978323, 12.97034507,  9.97565958,  9.97565958, 11.98695249,
        11.8990132 ,  9.97565958,  9.97565958, 11.91706476, 10.91155378,
         9.97565958, 11.38215145,  9.97565958,  9.97565958,  9.97565958,
         9.97565958,  9.97565958, 16.56691362, 10.12066751,  9.97565958,
        11.87006024,  9.97565958, 13.09818697,  9.97565958,  9.97565958,
         9.97565958, 13.38591582, 17.49040014,  9.97565958,  9.97565958,
        10.22317257, 13.88312785,  9.97565958, 10.42482477, 10.94443286,
        13.884551  ,  9.97565958,  9.97565958, 13.22976778,  9.97565958,
        10.53971169, 16.06344627, 17.41637944, 12.64468728,  9.97565958,
        12.25836558, 13.42098748, 13.79078882, 12.49506072, 10.78275677,
        11.23317629, 11.53154154, 10.97546763, 15.00491495,  9.97565958,
         9.97565958, 13.78590081,  9.97565958, 12.75410524, 12.74683941,
        10.11983434,  9.97565958,  9.97565958, 16.86508271,  9.97565958,
        15.25623441,  9.97565958, 16.60618568,  9.97565958,  9.97565958,
        11.27288853,  9.97565958, 10.95352145, 11.42793026, 17.19172569,
         9.97565958, 11.04556234, 10.3383521 , 12.7745725 , 12.26070194,
         9.97565958, 10.70640022,  9.97565958, 11.12037546, 12.79908607,
        10.47143541, 16.42717866,  9.97565958, 11.1482248 , 12.11315514,
        13.03794349,  9.97565958, 11.98644183, 11.41196228, 12.51536703,
         9.97565958, 11.94763047, 14.51746747, 10.42605268, 13.76390148,
        14.0939867 , 10.55193634, 10.65498488, 10.65601278,  9.97565958,
        11.31162224, 13.49656182, 13.85910957, 12.29863487,  9.97565958,
         9.97565958, 13.19112394, 12.59473678, 13.3210707 , 13.16187343,
        11.33364678, 15.7811    ,  9.97565958,  9.97565958, 12.95418428,
        13.46329589, 10.89456271,  9.97565958,  9.97565958, 10.53114945,
        12.30817737, 16.7157405 ,  9.97565958, 13.02389138,  9.97565958,
        11.76495614, 17.2991513 ,  9.97565958, 13.26850328,  9.97565958,
         9.97565958, 14.16123963, 11.5912912 ,  9.97565958, 12.89903369,
        15.8310652 , 10.45267729, 13.60720075, 15.45100049, 10.17030895,
         9.97565958,  9.97565958, 13.81906688,  9.97565958, 11.17747759,
        12.2162966 ,  9.97565958, 10.7122958 ,  9.97565958,  9.97565958,
        13.09701822,  9.97565958,  9.97565958,  9.97565958, 10.47265501,
        13.6713085 , 12.73887688,  9.97565958, 12.49094396,  9.97565958,
         9.97565958, 10.13737275, 13.84929437, 13.75757825, 17.13526349,
        10.70989791,  9.97565958,  9.97565958,  9.97565958,  9.993585  ,
         9.97565958, 10.97037769, 10.92666962,  9.97565958, 11.09260823,
         9.97565958,  9.97565958,  9.97565958, 12.5012178 , 10.21479206,
         9.97565958, 10.91382297,  9.97565958, 10.33924892,  9.97565958,
        17.5898811 , 11.18214284, 11.23533698, 12.24799262, 15.94691672,
        10.35165026,  9.97565958, 13.73636792, 16.3321004 ,  9.97565958,
         9.97565958, 10.41438668, 13.01912144, 17.28711596, 16.34284274,
         9.97565958, 11.28530007,  9.97565958, 13.71104368,  9.97565958,
        17.56361205, 10.61696234,  9.97565958, 10.09000327, 11.65393767,
        15.52587135, 15.60353223,  9.97565958, 12.91592323, 16.17869377,
        14.17112878, 17.34280162,  9.97565958,  9.97565958,  9.97565958,
        10.91997874, 11.68661681, 10.52969153,  9.97565958,  9.97565958,
        15.39256293, 17.12227775, 13.10105484, 15.72883017, 10.7952956 ,
        10.53799897,  9.97565958, 14.98020969,  9.97565958,  9.97565958,
        15.49208391,  9.97565958, 12.70333373, 10.26542107, 10.32526258,
         9.97565958,  9.97565958, 12.07488455,  9.97565958,  9.97565958,
        13.06109593, 17.12699538, 11.42585625, 11.36102565,  9.97565958,
        14.86195151,  9.97565958,  9.97565958,  9.97565958,  9.97565958,
        12.8267471 ,  9.97565958, 12.4035911 ,  9.97565958, 13.76791879,
         9.97565958, 11.19705566, 13.74229995,  9.97565958,  9.97565958,
         9.97565958,  9.97565958,  9.97565958, 10.20054896,  9.97565958,
        11.01740052,  9.97565958, 12.64234202, 16.32486981,  9.97565958,
        11.76197637, 17.67828823, 13.93969331, 14.26761992, 13.49358659,
         9.97565958, 12.2881965 , 10.59794208, 13.99770861,  9.97565958,
        11.08845292,  9.97565958, 12.44481556, 12.06732622, 13.46990942,
         9.97565958, 15.16895504, 10.75625872,  9.97565958,  9.97565958,
         9.97565958, 13.55721554,  9.97565958, 15.06035577,  9.97565958,
        12.77018624, 14.864076  , 11.19882269,  9.97565958,  9.97565958,
         9.97565958, 12.82357501,  9.97565958, 13.79019395,  9.97565958,
         9.97565958, 12.98661954,  9.97565958,  9.97565958, 13.58863444,
         9.97565958,  9.97565958, 12.89918505,  9.97565958, 10.83373105,
         9.97565958, 15.57987081,  9.97565958, 12.24942525, 13.13774433,
        10.24701557, 11.45129553, 13.46730627, 13.21358229,  9.97565958,
        12.93870081, 12.4956441 , 11.71425277, 10.20476395, 10.75354936,
         9.97565958, 15.75314214,  9.97565958,  9.97565958,  9.97565958,
         9.97565958, 11.17721913, 10.07931159, 11.76449165,  9.97565958,
        12.68856169, 13.18923536, 14.54583991, 11.77239358, 12.51032587,
        15.0430019 , 14.79365433, 10.30058681, 13.05513441,  9.97565958,
        12.60210772,  9.97565958,  9.97565958, 13.99001569, 12.11639546,
         9.97565958,  9.97565958, 15.14417906,  9.97565958, 10.62376849,
         9.97565958, 13.56758631, 10.64252948, 11.95125538, 11.86352339,
        13.09670436, 12.37696051,  9.97565958,  9.97565958, 11.38617054,
        10.32501516,  9.97565958,  9.97565958,  9.97565958,  9.97565958,
        11.52742717,  9.97565958, 13.80071516, 12.02489433, 16.00703476,
        12.84747845, 15.75299456, 13.44286055, 13.40694364, 15.69013931,
         9.97565958, 14.02221589, 12.96195769,  9.97565958, 10.05807227,
        16.92958097, 14.82777417,  9.97565958,  9.97565958, 12.70900592,
        12.25215438, 17.51853315,  9.97565958, 12.54734446, 10.08023582,
        13.26627247,  9.97565958, 16.41547002, 14.4285397 , 11.81757478,
        10.38831895, 11.93280492, 12.89989679, 11.26201196, 10.6228103 ,
        15.32428304,  9.97565958, 12.40955245, 10.12724203,  9.97565958,
         9.97565958, 16.99459092, 15.63216373, 11.76673713,  9.97565958,
        11.97696422, 14.99058325, 14.86402971, 12.01088689,  9.97565958,
        13.10785302,  9.97565958, 13.00188306, 11.23364152,  9.97565958,
        16.88326227, 11.39499669,  9.97565958, 13.18284039, 12.37558032,
        13.85286048, 17.01264007, 12.95421718, 15.31017443,  9.97565958,
        15.40331386, 10.96171678, 10.46024776,  9.97565958,  9.97565958,
         9.97565958, 11.29209231, 10.12395704, 15.69652679,  9.97565958,
        12.150477  , 13.15586761, 14.94778375, 14.37110033, 10.67087349,
        11.63765392, 17.00664773,  9.97565958,  9.97565958, 16.13419664,
        16.89267844, 13.39314687, 13.40687981, 12.49989409, 16.18019237,
         9.97565958, 13.85163289,  9.97565958, 10.81447183, 15.59747331,
        16.14675954, 13.60971356, 10.4318057 ,  9.97565958,  9.97565958,
        12.82273258, 12.17465763, 12.60014657,  9.97565958, 13.86114296,
        10.48746387, 13.8159025 , 12.92830624, 10.44587545, 16.05306139,
         9.97565958,  9.97565958, 10.35318988,  9.97565958, 16.89278246,
        13.87428726,  9.97565958,  9.97565958, 13.21569808, 13.27316617,
         9.97565958, 15.66846787, 12.31638323, 14.71867157,  9.97565958,
        16.77067106, 12.30487956,  9.97565958, 12.58350096, 13.88246359,
        16.82276247, 11.87434833,  9.97565958,  9.97565958, 11.54015012,
         9.97565958, 13.07613496, 14.57507625, 12.5648947 , 16.68805304,
         9.97565958, 13.49076308, 12.09301547, 13.65674302,  9.97565958,
        11.52977678, 13.06336949,  9.97565958, 10.01720376, 12.21720691,
        15.13731862, 11.04490255, 13.29734439, 13.32979283,  9.97565958,
         9.97565958, 14.51709931, 13.80139968,  9.97565958,  9.97565958]))

In [387]:
grader.check("q1")

q1 results: All test cases passed!

### Question 2

Now, you will engineer features from the other columns and use them to train a regression model.  Create a `Pipeline` that:
1. uses `'c1'` as is,
1. log-scales `'c2'`,
1. one-hot encodes `'group'`, and
1. predicts `'y'` using a linear regression model built on the three variables above. (Note that your model will have more than three "features", because one-hot encoding `'group'` will create multiple columns. Don't drop any of them.)

That is, complete the implementation of the function `multi_type_pipeline`, which takes in a DataFrame like `data` and returns a **tuple** consisting of
- An already-fit `Pipeline`, and
- An array containing the predictions your model makes on `data` (after being trained on `data`).

***Hint***: Use `ColumnTransformer`, as we did in [Lecture 14](https://dsc80.com/resources/lectures/lec14/lec14.html#Planning-our-first-ColumnTransformer).

In [388]:
# don't change this cell, but do run it -- it is needed for the tests to work
q2_fp = Path('data') / 'toy.csv'
q2_data = pd.read_csv(q2_fp)
q2_pl, q2_preds = multi_type_pipeline(q2_data)

In [389]:
multi_type_pipeline(q2_data)

(Pipeline(steps=[('predecessor',
                  ColumnTransformer(remainder='passthrough',
                                    transformers=[('log_c2',
                                                   FunctionTransformer(func=<ufunc 'log'>),
                                                   ['c2']),
                                                  ('ohe_group', OneHotEncoder(),
                                                   ['group'])])),
                 ('predict_y', LinearRegression())]),
 array([13.18531033, 14.74441827, 15.42116947, 12.83429335, 13.03799741,
        12.25310004, 12.43767512,  8.74186776, 14.83866743,  8.43157896,
        14.45273363, 11.75741912, 14.93030885, 13.26345315, 15.44172887,
        15.73687497, 11.62811781, 13.94580247, 13.31105138, 10.78091375,
        11.7671027 ,  9.8941669 , 11.89697715, 14.75691376, 13.9173444 ,
         8.33272857, 12.29120177, 12.75076932, 16.93692483,  9.38692656,
        16.41488837, 14.48484395, 13.97972499, 15.37545555, 11.73064088,
         8.51307035,  8.33440007, 15.31917206, 16.2222295 , 11.05978077,
         8.30549967, 15.82504116,  8.53576633, 14.97654842, 11.90167448,
        11.84565315, 10.64367785, 11.94487026, 11.77943364, 12.28160821,
         8.2717144 ,  9.39694084,  9.37574575,  8.18938447, 16.03260617,
        10.26170311, 16.00340929,  9.13893949,  8.68829782,  9.31903673,
         8.22310871, 12.32226532,  8.88997857,  8.21400817, 12.83686165,
        16.40954262, 11.23785325, 15.27415617, 16.43653785, 10.93296329,
        15.12431287,  9.49143228, 11.08209631,  8.24193682,  9.31353805,
        12.15382791, 12.59110382, 12.32111891, 11.7893595 , 12.15558619,
        11.73738008, 11.10105561, 15.54540115, 12.31248341, 15.33758984,
        12.46931485, 12.66027011, 11.54521595, 14.0015667 ,  9.10892195,
        11.5041973 , 12.56002948,  9.29213751,  8.94283595,  8.36278755,
        16.46262939, 12.66078586,  8.29185556,  9.2124712 , 14.3715037 ,
        12.76514656, 16.39220462,  8.66682226, 11.51237784, 11.44538124,
         8.88367454,  8.94014148, 15.61944071, 16.30317639, 13.28898107,
        14.51456068, 11.63732701,  8.49012059, 12.67347879, 14.75417662,
        12.85495414, 16.08869089,  7.86122092,  8.10558003, 15.62873131,
        15.30609172, 15.70696258,  8.95018795, 11.98051444,  9.19657028,
         8.60302749, 15.04155903, 13.71727441, 14.79361518, 13.37013282,
        16.16493007, 15.27767919, 12.18392834,  8.5075196 , 15.14552681,
        11.40289292, 15.58618929, 11.73769378,  8.60329136,  8.53472945,
        16.11181644, 11.29230541,  8.75375335, 11.26208747,  8.53005654,
         8.75492311, 15.57181131, 14.57087334,  8.37667743, 14.80589441,
         8.89632078, 15.51086594,  8.67148358, 12.81743766, 14.800459  ,
        11.65747044,  8.99466866, 12.39506247, 12.60905501,  8.96220362,
         8.41617312, 11.58083447,  8.73685686, 15.43515837, 12.06115976,
        12.44626129, 10.80153858,  8.89529039, 11.84431585,  8.89501844,
         7.86743289, 11.77965879, 15.97390235, 14.1598465 , 16.29431876,
        12.18159324, 11.12203048, 14.00032442, 11.69887821, 10.46015853,
        13.93416517, 14.07646803, 15.05914819, 14.67019898,  9.35294611,
        16.35826335, 15.60830669,  8.56156273,  8.90720223, 13.443261  ,
        13.0273128 ,  8.90597237, 14.46434301, 11.57489532, 11.87527462,
        12.03499763, 11.41051618, 14.07076799, 16.58767413, 17.1047704 ,
        11.90323652, 14.00815427, 12.37847795, 15.88835619, 15.76678045,
         8.79533732,  8.4047718 ,  7.64216447, 13.41567876, 16.85547664,
        16.3077274 , 14.59708095, 12.00664589, 11.76585786, 12.05042972,
        14.39520424, 15.69961359, 15.4034621 ,  8.51699688, 11.88243869,
         8.23559067,  8.86646142, 13.04767599, 11.43459629,  8.46824686,
        11.78731647, 12.56749263, 12.59293169, 12.61200289, 12.95997383,
        10.76070021,  9.60087135,  9.15311812, 12.33728853, 11.27599988,
        14.87129505, 16.57654423, 11.91437552, 16.22088206,  8.38866562,
        12.59000437, 12.2826393 , 15.30380188, 15.42792525,  8.74401617,
        11.5735807 ,  9.099614  , 15.35200453,  9.51605567,  7.79643788,
        14.22293348, 11.22572638,  9.05996936, 12.3555144 ,  9.50141587,
         8.19106534, 12.62877034, 10.30308635,  8.81171221,  9.67996417,
         9.00807833,  8.71177249, 11.35091577, 14.08882437,  8.73604303,
        12.70971279,  8.36951799,  8.75123334,  8.26847113, 10.95579146,
         8.78693972, 12.03389324, 12.67301526, 15.09445681, 13.17980653,
         8.63301654, 17.09516377, 16.01009363,  8.12041034, 12.17391419,
        13.870609  , 11.73966434, 11.8338333 ,  8.59254327, 15.28915797,
         8.69911259, 16.82870018,  8.48466188,  9.19064217, 11.80579673,
        16.58588129, 13.61786867, 14.33512515,  8.51689106, 14.50698687,
         8.14691267, 12.15341099,  9.26451048, 16.08899298, 13.78982825,
        11.50474808,  8.65790533, 14.54628593, 11.59164041, 11.79738539,
         8.46218536,  9.06376676, 14.37383461,  9.1843798 ,  8.53247932,
        15.93128806, 13.98419665, 11.67922264,  8.31801942, 16.18406532,
         8.87567094, 11.93892075,  8.37356438, 14.364156  , 14.67588705,
        15.74980059, 11.5271299 , 14.59978997,  8.45582871,  9.69351613,
        13.38574251, 14.9652951 , 12.47542493,  9.04869004, 16.27521922,
         9.30546826, 16.79850469, 12.8482356 , 15.45334449,  8.28027448,
        11.72345639, 11.76968366, 12.18633826, 12.48539295, 11.57237387,
        16.3032669 , 12.58019114, 11.80180368,  9.18010378, 11.40320037,
        16.65980554, 11.25713629, 14.79894391, 10.55361665, 11.73997974,
        14.77916196, 14.12809114, 13.44926468,  8.2899103 , 15.364999  ,
         8.32367777, 15.01524531, 10.51200827, 16.23838227, 11.67800935,
        12.98969784, 15.91394299,  8.38967435,  8.3999171 , 10.58129712,
        12.06575059, 15.62228414, 12.44884235,  8.8045582 ,  9.0032508 ,
        15.26677333, 15.66469059, 14.60004918, 12.41008707,  9.12532031,
         7.91465548, 11.74328074, 11.50200828,  8.75524516,  9.21912099,
        15.86161222,  7.99292554, 13.58010878, 11.63270394, 15.30557207,
        15.12401433,  9.31752349, 14.82532103, 15.76078396,  8.83962032,
        14.96911278, 16.59166094, 14.46917165, 12.25216689, 14.55274569,
        15.09036929,  8.09242662, 11.83944765, 12.63301826,  8.89683956,
         8.65394766, 15.08880571, 10.44423279, 16.22569617, 16.2613389 ,
        15.59390127, 13.05504998, 16.04153292, 15.68004612, 12.21463133,
        15.84518399,  8.43698594, 12.43627458, 12.93820962, 11.30303866,
        14.51861293, 14.97317714, 12.92542387,  9.08469663,  8.93204905,
         8.65419876, 16.88909323, 12.09455801, 11.83171288, 13.55456145,
        11.57351561,  9.28708604,  8.84739622, 13.0151064 , 14.87822967,
        14.27313279, 11.96157639, 12.63965437, 16.63115969, 12.94096166,
         8.94632481, 11.94567556,  8.57517433, 15.94864332, 11.08734888,
        13.55994403,  8.26940896, 10.23262703,  8.31148782, 12.44636458,
        15.08786395, 11.7303241 ,  8.1467382 , 14.61886669, 11.38220983,
         8.47668195, 16.22942701, 12.21586604,  8.99493803, 16.0959814 ,
        15.91292331, 13.14973747,  8.71020978,  8.17766722, 12.01470988,
        12.39656778,  8.72461126,  8.7729374 , 11.59445413, 14.3401658 ,
         8.67324916, 11.32910819,  8.66557076,  8.55881672,  8.30778484,
         9.23394874,  8.65580244, 16.08934691, 11.64747452,  8.18101053,
        12.28603286,  8.75121651, 15.06749275,  9.35893052,  8.20562329,
         8.38798554, 12.0797865 , 16.38169511,  9.02352622,  9.238541  ,
        13.6287461 , 15.3680564 ,  9.11702031, 11.29499833, 11.41982047,
        12.69382659,  8.86460845,  8.18415951, 12.52504123,  9.0588716 ,
        11.49489523, 16.43541322, 16.77287569, 14.5302961 ,  8.22059408,
        11.87148898, 12.72618844, 13.50900517, 11.95022041, 13.92095639,
        12.11146646, 12.1819225 , 12.03064631, 15.81743361,  9.13875989,
         9.05238009, 12.76200526,  8.90041135, 12.48618168, 12.34937631,
        11.94396512,  8.65937425,  8.46649209, 16.07096273,  9.02154479,
        15.80024836,  8.69068817, 13.62698958,  8.0972348 ,  9.10847772,
        11.48431088,  8.84996296,  9.25949345, 12.02899471, 15.92255796,
         9.03400937, 11.74539846, 14.23403679, 12.54357267, 14.72486212,
         8.15668819, 13.53972869,  8.85758092, 11.44889081, 13.06625406,
        11.7535339 , 16.42902428,  9.10423061, 11.64748364, 12.02852476,
        15.09256794,  8.79816779, 12.09323148, 11.5015536 , 10.18120767,
         8.69470115, 14.1368787 , 15.47523139, 11.34445627, 12.25769413,
        11.18856659, 12.51719873, 12.17717453, 13.6806179 ,  9.12139169,
        12.15526117, 12.35123229, 15.57441369, 12.44322768,  8.27645216,
         8.82796421, 12.52868916, 12.21543373, 12.44176797, 14.40755477,
        12.22539791, 15.6069669 ,  8.23097888,  8.0737384 , 14.47650208,
        10.31522923, 14.6438708 ,  8.2645855 ,  9.2288236 , 13.74832791,
        12.65837488, 15.61327055,  8.34220347, 12.89287407,  8.52481252,
        14.38208984, 16.45959717,  8.717192  , 12.7997059 ,  9.80093277,
         9.29899772, 15.447747  , 14.26025861,  8.55842699, 12.37676499,
        15.19853443, 11.04528893, 12.13010158, 15.87020597, 11.89012204,
         8.95142589,  9.37909409, 15.30542644,  8.94237972, 11.62900843,
        12.52353074,  8.41057342, 12.21108781,  8.49095656,  8.70277405,
        12.65943325,  9.01431759,  8.57077016,  8.62078917, 12.20499122,
        12.26974858, 14.70030969,  9.30791958, 11.93637538,  7.97912105,
         9.13255756, 13.62623274, 13.49212814, 13.20145549, 16.68077793,
        13.51571018,  8.29298368,  8.53272733,  8.89110921, 11.59747124,
         8.63603277, 14.39753836, 14.18008496,  9.41749823, 11.85665558,
         9.79437557,  8.99342303,  9.04736122, 11.87781358, 13.36349767,
         9.11592663, 12.20437956,  8.06209264, 13.92288291,  8.67020648,
        16.64634665,  9.60765114, 12.1090639 , 14.26148852, 15.67463251,
        10.95614944,  8.98143343, 12.05353081, 15.80429605,  8.71994549,
         8.23588337, 11.69541329, 12.62438647, 16.16853108, 15.5116485 ,
         8.80676928, 12.79100452, 12.90555413, 12.58923348, 14.12215341,
        15.96857859, 10.91635515,  9.29449489, 11.25386236, 12.82172692,
        15.79006237, 16.36700664,  8.99750332, 10.33051291, 17.23275483,
        14.4686284 , 16.626169  , 12.86290695,  8.48237032,  8.52780735,
        13.69186209, 14.81868484, 11.82396863,  8.9958492 ,  8.08327082,
        15.20835326, 15.77008438, 12.47156425, 14.81872025, 11.85553393,
        11.09984473,  9.39078067, 15.34133371,  8.50745247,  8.76734743,
        16.02209123,  8.42233806, 12.46646655, 11.67266278, 11.57194557,
         9.66726341,  8.01446895, 12.3703077 ,  9.11582296,  8.41312886,
        14.23950316, 15.43457051, 11.86683203, 15.30575792,  9.04088918,
        15.58812642,  9.11136933,  8.12221277,  8.72101538,  9.25193819,
        14.03593335,  9.34685502, 14.64846309,  9.03221978, 13.38603821,
         9.52444292, 14.38992864, 14.6235555 ,  8.97341933,  9.45090224,
         8.66952976, 11.78832709,  9.52583584, 11.15900554,  9.70242408,
        11.14921781,  8.35191969, 12.10503925, 15.36112788,  8.92860541,
        14.8356975 , 16.78631072, 15.4413865 , 15.87271642, 13.20650787,
         8.70022523, 12.67366047, 11.4183288 , 14.9976053 , 11.13599497,
        11.52755345,  8.5529462 , 12.81899181, 11.81419499, 12.16233312,
         8.05048204, 15.33170575, 11.58460083,  8.55187709,  8.04560081,
         9.15906596, 15.32873137, 11.09597575, 15.96440385,  9.36891352,
        12.93262789, 10.84544925, 11.77936413,  8.74500215,  9.11974154,
        12.57059285, 12.42260787,  8.82012413, 15.55156709,  9.07525097,
         8.63889945, 14.75137666,  9.14063331, 10.87331338, 12.9699804 ,
         9.21023034,  8.68494964, 12.31674386,  8.58958887, 12.27245111,
         8.77208195, 16.28783796,  8.61012606, 14.6861854 , 12.64565042,
        14.31244384, 13.82042262, 15.32978386, 12.30626115,  8.16724436,
        12.17641795, 13.05289466, 12.44520155, 10.99688344, 12.40456004,
         9.12399789, 15.52618576,  9.01852006,  9.06804219,  8.56297859,
         8.79822264, 14.93131614, 12.07153002, 14.2371385 ,  9.21920144,
        12.01328924, 13.02803669, 14.94396422, 14.36799317, 12.53680686,
        15.55355408, 15.62020734, 11.25326614, 14.87049414,  9.02275181,
        11.44756547,  9.03580153,  8.76245303, 15.44102457, 11.95324753,
         8.22421166,  8.39010225, 15.86814121,  9.04815459, 14.45331915,
         8.80090235, 14.72665075, 11.74080257, 11.5374267 , 14.15371028,
        11.91106446, 12.40350672,  8.5491043 ,  8.21631232, 11.40709009,
        10.94249204,  8.16800401,  9.25061617,  8.62094656,  9.36993444,
        12.14875993,  8.67423366, 13.02138638, 12.33226532, 16.52424546,
        12.31404327, 15.89962798, 15.33293562, 12.2847212 , 16.68448936,
         9.28923419, 15.04623631, 13.1465683 ,  8.84179786, 11.55702768,
        15.80622151, 11.20137648,  8.6864736 ,  8.8320998 , 14.81541656,
        12.67936995, 16.59752678,  7.95025692, 15.11811409, 13.85061818,
        12.21926568,  8.27398033, 16.03194083, 15.97141362, 11.99104296,
        11.39428478, 11.7755808 , 12.14771739, 12.44612034, 11.60257254,
        15.3079988 ,  9.05374962, 12.31097367, 14.00694103,  8.5710332 ,
         8.56332699, 15.8443658 , 15.63490127, 11.85548513,  8.81507025,
        14.09408554, 15.21611334, 15.41854951, 11.64017405,  8.65975835,
        12.50884054,  8.54118799, 14.14869452, 10.8271904 ,  9.25415584,
        16.09364693, 10.31162318,  8.88188214, 16.02897909, 10.31474869,
        12.84429698, 12.08975196, 12.33951279, 15.32950486,  8.68919083,
        14.20200419, 11.81110905, 11.42330814,  8.88253845,  8.04330293,
         8.47434517, 12.46678487, 11.0658471 , 15.75968321,  8.44195758,
        12.47016025, 12.40582732, 16.12994089, 15.56918645, 14.0820919 ,
        14.20632857, 16.52015213,  9.16669178,  8.89760772, 13.97195078,
        15.99987912, 10.41845878, 14.7204974 , 15.25816654, 16.40708134,
         8.48887202, 15.26456872,  8.70465627, 11.59711747, 16.30121647,
        15.90457021, 12.56506544, 11.886063  ,  8.60220914,  8.79783368,
        12.35777538, 12.28758356, 12.68455233, 10.65336922, 12.74799376,
        13.90097759, 12.30397277, 12.45827093, 14.60830409, 15.51488919,
         8.4057284 ,  8.98971064, 11.18707131,  8.08928616, 16.45496525,
        14.96363684,  9.78653625,  8.86735368, 10.33125266, 11.68579994,
         8.58619532, 15.8967992 , 12.48873544, 15.40471921,  9.26592691,
        16.61003672, 11.85877411,  8.74509309, 11.81239345, 15.28409018,
        16.32446224, 14.47576512,  7.7709899 ,  8.35137048, 14.05741502,
         9.23504339, 12.4579996 , 15.78414898, 12.05972424, 16.33819519,
         8.44751295, 14.41261526, 14.1013425 , 15.26079488, 12.81440981,
        12.1871229 , 12.39293456,  9.28942874, 11.15494183, 12.08586595,
        15.22711473, 13.46305888, 15.08745913, 12.35067835,  8.47955491,
         8.51958678, 15.46545611, 12.87990534,  9.14020879,  9.11238125]))

In [390]:
grader.check("q2")

q2 results: All test cases passed!

### Question 3

It seems like `'c1'` and `'c2'` have strong associations with the values of `'group'` (to see this, run the cell below). This suggests that group-wise scaling might make good features. 


Now, we want to standardize (i.e. z-score) both `'c1'` and `'c2'` **within each `'group'`** (`'A'`, `'B'`, and `'C'`). Unfortunately, there is no built-in transformer in `sklearn` that performs group-wise standardization, so **you will need to create your own transformer!**

Your job is to complete the implementation of the `StdScalerByGroup` transformer class, meaning that you need to implement the `fit` and `transform` methods, along with the constructor (`__init__`).
- The `StdScalerByGroup` transformer works on an input array/DataFrame `X` whose first column contains groups, and whose remaining columns are quantitative and need to be standardized (within each group).
- The `fit` method should determine the mean and standard deviation of each quantitative column within each group in the input data `X` and save them in the instance variable `grps_`. (For instance, one of the quantities you may calculate here is the standard deviation of `'c1'`, but only for the rows whose `'group'` is `'B'`.)
- The `transform` method should take in an input array/DataFrame `X`, standardize each quantitative column separately using the means and standard deviations stored in `grps_`, and return a DataFrame containing the transformed quantitative columns.


If you `fit` and `transform` a `StdScalerByGroup` transformer on the `toy` DataFrame (without the `'y'` column), you should get back a DataFrame with two columns, `'c1'` and `'c2'`, with groups stored in the index (if you end up creating a `MultiIndex`, that is fine).


***Notes:***
1. You may decide on whatever structure you'd like for the `grps_` variable. This question will be graded on the correctness of the output of your transformer. (Check the correctness of your work by checking the output by-hand!)    
2. At no point should you loop over the **rows** of `data` (in fact, our solution doesn't use any loops), but you are allowed to use loop in this question.
3. The `'group'` column in the public tests is named `'g'` instead of `'group'`. Remember, the first column will **always** contain the groups, even if the first column's name is something other than `'group'`.
4. Don't worry about cases where the standard deviation is 0.

In [391]:
# The scatter plot referenced at the start of Question 3
# This is not needed to answer the question, but motivates why we are standardizing
px.scatter(data, x='c1', y='y', color='group')

In [392]:
# don't change this cell, but do run it -- it is needed for the tests to work
# test fit 
q3_test_fit_cols = {'g': ['A', 'A', 'B', 'B'], 'c1': [1, 2, 2, 2], 'c2': [3, 1, 2, 0]}
q3_test_fit_X = pd.DataFrame(q3_test_fit_cols)
q3_test_fit_std = StdScalerByGroup().fit(q3_test_fit_X)

# test transform
q3_test_transform_cols = {'g': ['A', 'A', 'B', 'B'], 'c1': [1, 2, 3, 4], 'c2': [1, 2, 3, 4]}
q3_test_transform_X = pd.DataFrame(q3_test_transform_cols)
q3_test_transform_std = StdScalerByGroup().fit(q3_test_transform_X)
q3_test_transform_out = q3_test_transform_std.transform(q3_test_transform_X)

In [393]:
# don't change this cell, but do run it -- it is needed for the tests to work
q3_fit_data = pd.read_csv(Path('data') / 'toy.csv')

N = 2*10**6
a = np.random.choice(['A', 'B'], size=(N,1)).astype('object')
b = np.random.multivariate_normal([1, 2], [[1, 0],[0, 100]], size=N)
arr = np.hstack([a, b])
q3_transform_data = pd.DataFrame(arr)
q3_transform_data[1] = q3_transform_data[1].astype(float)
q3_transform_data[2] = q3_transform_data[2].astype(float)

In [394]:
grader.check("q3")

q3 results: All test cases passed!

### Question 4

`Pipeline`s are supposed to help you easily try different model configurations. Complete the implementation of the function `eval_toy_model`, which returns a hard-coded **list of tuples** consisting of the (RMSE, $R^2$) of three different modeling `Pipeline`s, fit and evaluated on the entire input dataset `data`. The three different `Pipeline`s are:
1. The `Pipeline` in Question 1.
1. The `Pipeline` in Question 2.
1. A `Pipeline` consisting of a linear regression model fit on features generated by applying `StdScalerByGroup` to `'c1'`, log-scaling `'c2'`, and applying `OneHotEncoder` to `'group'`.

In [395]:
q2_4p = Path('data') / 'toy.csv'
q2_data = pd.read_csv(q2_4p)

In [396]:
from sklearn.metrics import mean_squared_error # New!
prec = ColumnTransformer(transformers=[
                                ('std_scalar',StdScalerByGroup(),['group','c1']),
                                ('log_c2',FunctionTransformer(np.log),['c2']),
                                ('ohe_group', OneHotEncoder(),['group']),
                                ],
                            remainder= 'passthrough')
plt = Pipeline([
    ('predecessor', prec),
    ('predict_y', LinearRegression()) 
    ])
x = q2_data.drop('y', axis=1)  # Assuming 'y' is the target variable
y = q2_data['y']

# Fit the pipeline on the data
plt.fit(x, y)
prediction = plt.predict(q2_data.drop('y',axis=1))
mean_squared_error(y, prediction, squared=False)
r_squared = plt.score(x, y)
r_squared

0.5729929650348397

In [397]:
grader.check("q4")

q4 results: All test cases passed!

## Part 2: Overfitting üòü

### Question 5

In this question, you will train two different classes of prediction models ‚Äì **decision tree and k-Nearest Neighbor regressors** ‚Äì and explore different ways in which overfitting can appear. You'll use Galton's child heights dataset from the missingness lectures and Lab 5.

#### `tree_reg_perf` üå≤

A decision tree regressor is trained similar to a decision tree classifier: the splits of the tree are created by minimizing the variance of the (training data) response values in the leaves given by making the split in question. A decision tree regressor predicts the response value of a (new) observation based on the **average target value** of the training observations lying in the same leaf node. 

One **hyperparameter** of a decision tree regressor that affects model complexity is the **depth** of the tree. Larger depths correspond to more complicated decision trees. We will explore this parameter in this question.

Complete the implementation of the function `tree_reg_perf`, which takes in a DataFrame like `galton` and:
- Splits the data into training and test sets,
- Trains 20 decision trees ‚Äì one for each depth between 1 and 20, and
- Computes both the training RMSE and test RMSE of each tree.

Store and return your results in a DataFrame that has two columns, `'train_err'` and `'test_err'`, and an index that corresponds to tree depths (i.e. 1, 2, ..., 20).

<br>

#### `knn_reg_perf` üëâüëà

A k-Nearest Neighbors (k-NN) regressor predicts the response value of a (new) observation by computing the average value of the k-closest observations in the training set. The most common distance metric is Euclidean distance, i.e. $L_2$ distance.

One **hyperparameter** of a k-NN regressor that affects model complexity is k, **the number of neighbors averaged over**. Larger values of k correspond to more complicated regressors. We will explore this hyperparameter in this question.

Complete the implementation of the function `knn_reg_perf`, which takes in a DataFrame like `galton` and:
- Splits the data into training and test sets,
- Trains 20 k-NN regressors ‚Äì one for each value of k between 1 and 20, and
- Computes both the training RMSE and test RMSE of each regressor.

Again, store and return your results in a DataFrame that has two columns, `'train_err'` and `'test_err'`, and an index that corresponds to values of k (i.e. 1, 2, ..., 20).

<br>

**Some guidelines for both subparts:**

- In all cases, we are using all other columns in `galton` to predict `'childHeight'`.
- You need to import the necessary classes from `sklearn` **inside** the functions you create. (Unlike before, we haven't imported them for you because we want you to figure out what to import!)
- If you're unsure how to create training and testing sets, refer to [Lecture 15](https://dsc80.com/resources/lectures/lec15/lec15.html#Train-test-splits). Use a test set size of 0.25. Within each function, you should only perform a single train-test split ‚Äì that is, you should not be creating training and testing sets within a `for`-loop (though you will need to use a `for`-loop for something else).
    - For the purposes of this question, do not use any cross-validation.
- Don't write the formula for RMSE four times ‚Äì define a helper function!

In [398]:
# Use `galton` to test your work.
galton = pd.read_csv(Path('data') / 'galton.csv')
galton.head()

   father  mother  children  childNum  gender  childHeight
0    78.5    67.0         4         1       1         73.2
1    78.5    67.0         4         2       0         69.2
2    78.5    67.0         4         3       0         69.0
3    78.5    67.0         4         4       0         69.0
4    75.5    66.5         4         1       1         73.5

In [399]:
tree_reg_perf(galton_test)

    train_err  test_err
1    2.478742  2.542062
2    2.305074  2.367729
3    2.142628  2.235068
4    2.000847  2.159482
5    1.848331  2.172736
6    1.682927  2.147298
7    1.501102  2.218254
8    1.298660  2.231941
9    1.095064  2.418369
10   0.886945  2.535351
11   0.706380  2.549084
12   0.535270  2.619781
13   0.418464  2.633162
14   0.303144  2.622355
15   0.244450  2.699033
16   0.203171  2.617846
17   0.193415  2.659632
18   0.190938  2.669354
19   0.190938  2.673631
20   0.190938  2.647838

In [400]:
# don't change this cell, but do run it -- it is needed for the tests
galton_test = pd.read_csv(Path('data') / 'galton.csv')
out_tree_test = tree_reg_perf(galton_test)
out_knn_test = knn_reg_perf(galton_test)

In [401]:
grader.check("q5")

q5 results: All test cases passed!

After you've implemented both functions, run the cells below to plot training and testing error for both models.

In [402]:
pio.renderers.default = 'browser'

In [403]:
np.random.seed(9) # For reproducibility

tree = tree_reg_perf(galton)
knn = knn_reg_perf(galton)
hyp = np.arange(1, 21)

fig = make_subplots(rows=1, cols=2, subplot_titles=('Error vs. Tree Depth for Decision Tree Regressor',
                                                    'Error vs. k (# Neighbors) for k-NN Regressor'))

fig.add_trace(
    go.Scatter(x=hyp, y=tree.iloc[:, 0], name='Training Error'),
    row=1, col=1).add_trace(go.Scatter(x=hyp, y=tree.iloc[:, 1], name='Test Error'), 
                            row=1, col=1)

fig.add_trace(
    go.Scatter(x=hyp, y=knn.iloc[:, 0], line=dict(color='#1f77b4'), name='Training Error', showlegend=False),
    row=1, col=2).add_trace(go.Scatter(x=hyp, y=knn.iloc[:, 1], line=dict(color='#ff7f0f'),  name='Test Error',
                                       showlegend=False), row=1, col=2)

fig.update_layout(height=600, width=975)
fig.update_xaxes(title_text='Tree Depth', row=1, col=1, tickvals=np.arange(1,21,2))
fig.update_xaxes(title_text='k (# Neighbors)', row=1, col=2, tickvals=np.arange(1,21,2))

fig.show()

If your training and evaluation routines are correct, you should notice a few things:
- In both models, test error initially decreases, and then (perhaps slowly) increases.
- With the decision tree, training error **decreases** as depth increases.
- With the k-NN regressor, training error **increases** as k (the number of neighbors looked at) increases.

You should think about **why** you observe each of the above phenomena. In particular, the last point may seem confusing ‚Äì one would think that because larger values of k correspond to more complicated models (because the regressor is looking at more information to make a prediction), larger values of k should have lower training errors. But the nature of k-NN regressors is quite different than, say, decision tree regressors or linear regression models.

Lastly, in both cases, identify the ideal **hyperparameter** choice based on the graphs of test error. You don't have to write the answer anywhere.

## Part 3: Predicting Survival on the Titanic üõ≥üßä

### Question 6

Predicting whether or not passengers on the Titanic survived is a common first assignment when learning about classification ‚Äì now it's your turn!

Complete the implementation of the function `titanic_model`, which takes in a DataFrame `titanic` containing **training data only** and returns a `Pipeline` object fit to the training data. 


#### Requirements

You have freedom to build your own model. That is, **you can use any classification algorithm**, but your model should satisfy the following requirements:

- The model is built on the (binary) response column `'Survived'`.
* The model uses features derived from **all other columns in `titanic`**. Below, we specify which columns to "engineer"; you may "engineer" features using other columns, but be sure to include every column in your model (even if you choose to leave some columns as-is).

* Required feature engineering:
    * Derive a feature from the "title" in the `'Name'` field (e.g. "Mr", "Miss", "Mrs" ‚Äì the names themselves should not be used as a feature; think about why).
    * Derive a feature that standardizes passengers' ages among their `'Pclass'` (use Question 3!).
    
#### Evaluation
    
Your model must achieve an accuracy of 0.78 on both the training set and the test set. Note that while you have access to the test set, it is still encouraged to perform your own model validation.

**Extra credit: If your model can consistently earn an accuracy of above 0.83 on the test set, you can earn 5 points of extra credit on the lab!** That is, you can earn up to 60 points on the lab, even though it is only graded out of 55 points (meaning you _can_ have a score above 100% on the lab).

Some guidance:

- `Pipeline` objects can have other `Pipeline` objects within them. While this isn't a requirement, you may find this useful to break down your model into smaller, more manageable steps.
    - You can even create a `Pipeline` made up of transformers only, if you want to perform multiple transformations on a single column. We did this in [Lecture 15](https://dsc80.com/resources/lectures/lec15/lec15.html#Standardization).
    - The function `make_pipeline` from [Lecture 15](https://dsc80.com/resources/lectures/lec15/lec15.html#%F0%9F%92%A1-Pro-Tip:-Using-make_pipeline) could also be useful.
- Your submitted `titanic_model` function should have the model's hyperparameters (e.g. tree depth) hard-coded in it. That is, the `Pipeline` object doesn't have to include the hyperparameter selection process.
- You will find the [`FunctionTransformer`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html) class useful. If you want your transformer to output a categorical feature, you may need to specify `validate=False`.
- When using the [`ColumnTransformer`](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html#sklearn.compose.ColumnTransformer) class , you may find the `remainder` keyword helpful.
- If you are set out to get those extra 5 points, consider building some meaningful features before fine-tuning the hyperparameters of your model. Do an EDA on the dataset ‚Äì what kinds of people are more prone to survive?

In [404]:
q6_data_test.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,2,Mr. William John Berriman,male,23.0,0,0,13.0000
1,1,3,Mrs. (Beila) Moor,female,27.0,0,1,12.4750
2,0,3,Mr. Nestor Cyriel Vande Walle,male,28.0,0,0,9.5000
3,0,3,Mr. Khalil Saad,male,25.0,0,0,7.2250
4,0,3,Miss. Gerda Ulrika Dahlberg,female,22.0,0,0,10.5167

In [405]:
# don't change this cell, but do run it -- it is needed for the tests
q6_data_test = pd.read_csv(Path('data') / 'titanic.csv')
pl_test = titanic_model(q6_data_test)

In [406]:
titanic_model(q6_data_test)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Name',
                                                  Pipeline(steps=[('Name',
                                                                   FunctionTransformer(func=<function titanic_model.<locals>.extract_name at 0x000001F432D03430>)),
                                                                  ('Nameohe',
                                                                   OneHotEncoder())]),
                                                  ['Name']),
                                                 ('Age',
                                                  Pipeline(steps=[('ageohe',
                                                                   StdScalerByGroup())]),
                                                  ['Pclass', 'Age']),
                                                 ('std', StandardScaler(),
                                                  ['Siblings/Spouses Aboard',
                                                   'Parents/Children Aboard',
                                                   'Fare']),
                                                 ('ohe', OneHotEncoder(),
                                                  ['Sex'])])),
                ('classifier',
                 RandomForestClassifier(n_estimators=1, random_state=42))])

In [407]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
model = titanic_model(q6_data_test)
x_trains,x_tests,y_trains,y_test = train_test_split(q6_data_test.drop('Survived',axis=1),q6_data_test['Survived'],test_size=0.2,random_state=42)
train_accura1cy = model.score(x_trains,y_trains)

test_accuracy = model.score(x_tests,y_test)
test_accuracy

0.9014084507042254

In [408]:
grader.check("q6")

q6 results: All test cases passed!

There is **a ton** of material out there on analyzing data from the Titanic. After you build your model, look online for other examples (e.g. [on Kaggle](https://www.kaggle.com/c/titanic)) and think about how you could improve your model.

## Congratulations! You're done Lab 9! üèÅ

As a reminder, all of the work you want to submit needs to be in `lab.py`.

To ensure that all of the work you want to submit is in `lab.py`, we've included a script named `lab-validation.py` in the lab folder. You shouldn't edit it, but instead, you should call it from the command line (e.g. the Terminal) to test your work.

Once you've finished the lab, you should open the command line and run, in the directory for this lab:

```
python lab-validation.py
```

**This will run all of the `grader.check` cells that you see in this notebook, but only using the code in `lab.py` ‚Äì that is, it doesn't look at any of the code in this notebook. If all of your `grader.check` cells pass in this notebook but not all of them pass in your command line with the above command, then you likely have code in your notebook that isn't in your `lab.py`!**

You can also use `lab-validation.py` to test individual questions. For instance,

```
python lab-validation.py q1 q2 q4
```

will run the `grader.check` cells for Questions 1, 2, and 4 ‚Äì again, only using the code in `lab.py`. [This video](https://www.loom.com/share/0ea254b85b2745e59322b5e5a8692e91?sid=5acc92e6-0dfe-4555-9b6a-8115b6a52f99) how to use the script as well.

Once `python lab-validation.py` shows that you're passing all test cases, you're ready to submit your `lab.py` (and only your `lab.py`) to Gradescope. Once submitting to Gradescope, make sure to stick around until all test cases pass.

There is also a call to `grader.check_all()` below in _this_ notebook, but make sure to also follow the steps above.

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [409]:
grader.check_all()

q1 results: All test cases passed!

q2 results: All test cases passed!

q3 results: All test cases passed!

q4 results: All test cases passed!

q5 results: All test cases passed!

q6 results: All test cases passed!